[profile.default]
src = "src"
out = "out"
# libs = ["lib", "dependencies"]
libs = ["dependencies"] # <= This is important to be added


[soldeer]
recursive_deps = true



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[dependencies] # <= Dependencies will be added under this config
"@openzeppelin-contracts" = { version = "5.6.1" }
"@uniswap-universal-router" = { version = "1.6.0" }
"@prb-math" = { version = "4.0.2" }
forge-std = { version = "1.16.0" }

